### PR TITLE
UI Code Cleanup & Added Polyline Tracking

### PR DESCRIPTION
**Pull request by nilsstreedain**

### CODE REVIEW

**Review by jackhart591 — COMMENTED** [review]
Bug where every 8~ seconds, my position jumps about 100ft west. I will approve after this is fixed.

**Comment by nilsstreedain** [comment]
> Bug where every 8~ seconds, my position jumps about 100ft west. I will approve after this is fixed.
This is likely GPS accuracy issues from interference on campus, additional iPhones older than the iPhone X generally have about a 15-25 meters accuracy under normal conditions. This issue could not been replicated on my device. Could you please submit screenshots of the issue, along with device information through the TestFlight app. Thanks!

**Comment by jackhart591** [comment]
> > Bug where every 8~ seconds, my position jumps about 100ft west. I will approve after this is fixed.
> 
> 
> 
> This is likely GPS accuracy issues from interference on campus, additionally iPhones older than the iPhone X generally have about a 15-25 meters accuracy under normal conditions. This issue could not been replicated on my device. Could you please submit screenshots of the issue, along with device information through the TestFlight app. Thanks!

Here is screenshots. I'm using an iPhone 11 on IOS 16.1imageimage

**Comment by nilsstreedain** [comment]
(Also I should note that the actual GPS position view is not dealt with by the app nor this PR)

**Review by jackhart591 — APPROVED** [review]
Resolved off of github.

**Pull request merged**
