### PR TITLE
Added Live Hike Stats

### PR DESCRIPTION
**Pull request by nilsstreedain**
Added live stats for hiking (calories ommited). Additionally, app location data was restructured so please fully delete any current build of the app before before installing this version.

### CODE REVIEW

**Comment by js567** [comment]
Noticing the same issue in the app, the hike resets after a few seconds.

**Comment by nilsstreedain** [comment]
Moved locationManager status check into LocationRequestView() to prevent ObservedObject repaint for LiveHikeView. Also removed CloudKit containers to reduce warnings on launch (Will add back later). Issue resolved in local testing, please test on your device **after** uninstalling the previous build.

**Review by js567 — APPROVED** [review]
Ran on my phone. Correctly prompts user for location. Timer, distance, pace, and elevation all seem to be working correctly. Did not test on an actual hike with a known distance.

**Comment by js567** [comment]
Looks solid, good work!

**Pull request merged**
